feat: enable whitesource scan
redhat-marketplace/datactl pull request #15
Opened 2022-07-13 19:39 UTC by MJSiddu

Ticket:
https://zenhub.ibm.com/workspaces/symposium-workflow-5c49e21b79c5ae72931da0d6/issues/symposium/track-and-plan/25345

2022-07-13 19:40 UTC, MJSiddu commented
@dacleyra - can you add API_KEY and USER_KEY under Secrets?

2022-07-18 09:04 UTC, ab-ibm requested changes

2022-07-18 09:04 UTC, ab-ibm commented on .github/workflows/go.yml
> +      env:
Invalid yaml file, looks like env is not properly aligned

2022-07-25 13:14 UTC, mxpaspa commented on .goreleaser.yml
> +    - go mod tidy -go=1.16 && go mod tidy -go=1.17
@dacleyra I added this to get around a go mod issue

2022-07-25 13:20 UTC, ab-ibm approved these changes

2022-07-25 13:57 UTC, MJSiddu commented
LGTM.

2022-07-25 14:13 UTC, dacleyra approved these changes

2022-07-25 14:14 UTC, merged